### ISSUE TITLE
Front-End-Checklist

### ISSUE THREAD

**Issue by padosum** [padosum/pocket-kyujanggak#4]
[Front-End-Checklist](https://github.com/thedaviddias/Front-End-Checklist)를 참고하여 작업 

### Meta tag
* [x] Doctype
* [x] Charset
* [x] Viewport
* [x] Title
* [x] Description
* [x] Favicons
* [x] Apple Web App Meta
* [ ] Windows Tiles
* [ ] Canonical

### HTML tags
* [x] Language attribute
* [x] Direction attribute
* [ ] Alternate language
* [ ] x-default
* [ ] Conditional comments
* [x] ~~RSS feed~~
* [ ] CSS Critical
* [ ] CSS order

### Social meta
* [ ] Facebook Open Graph
* [ ] Twitter Card

### Best practices
* [x] HTML5 Semantic Elements
* [ ] Error pages
  * [x] 404
  * [ ] 5xx
* [x] Noopener
* [x] Clean up comments

### HTML testing

* [x] W3C compliant
* [x] HTML Lint
* [x] Link checker
* [x] ~~Adblockers test~~
---

## Webfonts
* [x] Webfont format
* [x] Webfont size
* [x] ~~Webfont loader~~

---

## CSS
* [x] Responsive Web Design
* [ ] ~~CSS Print~~
* [x] ~~Preprocessors~~
* [x] Unique ID
* [x] Reset CSS
  - [Normalize.css](https://necolas.github.io/normalize.css/)
* [x] JS prefix
* [x] embedded or inline CSS
* [x] Vendor prefixes

### Performance

* [x] Concatenation
* [x] Minification
  * vite.js
* [ ] Non-blocking
* [  Unused CSS

### CSS testing

* [ ] Stylelint
* [x] Responsive web design
* [ ] CSS Validator
* [x] Desktop Browsers
* [X] Mobile Browsers
* [] OS
  * [x] iOS
  * [x] Mac
  * [x] Windows
  * [ ] Android 
* [ ] Design fidelity
* [ ] ~~Reading direction~~

---

### Best practices
* [x] Optimization
* [ ] Picture/Srcset
* [ ] Retina
* [ ] Sprite
* [x] Width and Height
* [x] Alternative text
* [x] Lazy loading  #10

---
### Best practices

* [x] JavaScript Inline
* [x] Concatenation
  * vite.js
* [x] Minification
  * vite.js 
* [ ] JavaScript security
- 📖 [Guidelines for Developing Secure Applications Utilizing JavaScript](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet#Guidelines_for_Developing_Secure_Applications_Utilizing_JavaScript)
* [x] `noscript` tag
* [ ] Non-blocking
* [ ] Optimized and updated JS libraries
* [ ] Modernizr

### JavaScript testing
* [x] ESLint
---

### Scan and check your web site

> * [securityheaders.io](https://securityheaders.io/)
> * [Observatory by Mozilla](https://observatory.mozilla.org/)

### Best practices

* [x] HTTPS
* [ ] HTTP Strict Transport Security (HSTS)
* [ ] Cross Site Request Forgery (CSRF)
* [ ] Cross Site Scripting (XSS)
* [ ] Content Type Options
* [ ] Content Security Policy
---

### Best practices

* [ ] Goals to achieve
* [ ] Minified HTML
* [ ] Lazy loading
* [ ] Cookie size
* [ ] Third party components

### Preparing upcoming requests
* [ ] DNS resolution
* [ ] Preconnection
* [ ] Prefetching
* [ ] Preloading

### Performance testing

* [ ] Google PageSpeed

---

### Best practices

* [ ] Progressive enhancement
* [ ] Color contrast

#### Headings

* [x] H1
* [x] Headings

### Semantics

* [x] Specific HTML5 input types are used

### Form

* [x] Label

### Accessibility testing

* [ ] Accessibility standards testing
  * [Wave testing](http://wave.webaim.org/) 
* [ ] Keyboard navigation
* [ ] Screen-reader
* [ ] Focus style

---

## SEO

* [ ] Google Analytics
* [ ] Search Console
* [ ] Headings logic
* [ ] sitemap.xml
* [ ] robots.txt
* [ ] Structured Data
* [ ] Sitemap HTML
